automations:
  control: hidden
  view: yes
  entities:
    - automation.allumer_apres_coucher_du_soleil
    - automation.allumer_chauffage_sdb_parents_jours_non_travailles
    - automation.allumer_chauffage_sdb_parents_jours_travailles_et_philo_travaille_le_matin
    - automation.allumer_chauffage_sdb_parents_jours_travailles_et_philo_travaille_pas_le_matin
    - automation.allumer_chevet_basile_jour_non_travaille
    - automation.allumer_chevet_basile_jour_travaille
    - automation.allumer_chevet_basile_soir_veille_jour_travaille
    - automation.allumer_escalier_matin_samedi
    - automation.allumer_escalier_matin_semaine
    - automation.allumer_exterieur_entree_au_coucher_du_soleil
    - automation.allumer_exterieur_si_quelqu_un_rentre_apres_23h
    - automation.allumer_lapin_louise_matin_non_travaille
    - automation.allumer_lapin_louise_matin_travaille
    - automation.allumer_lapin_louise_soir_veille_jour_travaille
    - automation.allumer_le_sapin_quand_on_rentre
    - automation.allumer_pour_petit_dej_samedi
    - automation.allumer_pour_petit_dej_semaine
    - automation.allumer_sapin_si_qqun_a_la_maison
    - automation.arret_kodi_salle_familiale
    - automation.arret_kodi_salon
    - automation.effet_des_leds_de_la_salle_familiale
    - automation.envoyer_notif_expiration_certificat
    - automation.eteindre_chauffage_sdb_parents_apres_dix_minutes
    - automation.eteindre_cinema_maison_apres_1h
    - automation.eteindre_exterieur_a_23h
    - automation.eteindre_le_sapin_le_soir
    - automation.eteindre_le_sapin_quand_on_part
    - automation.eteindre_plafond_salle_familiale_apres_1h
    - automation.fermer_la_porte_patio_si_les_parents_ne_sont_plus_a_la_maison
    - automation.grader_escalier_les_soirs_de_semaine
    - automation.guillaume_plus_a_la_maison
    - automation.guillaume_plus_a_la_maison_maj_parents
    - automation.guillaume_retour_a_la_maison
    - automation.guillaume_retour_a_la_maison_maj_parents
    - automation.lecture_kodi_salle_familiale
    - automation.lecture_kodi_salon
    - automation.notfier_si_nas_devient_anormal
    - automation.notification_si_maj_disponible
    - automation.notifier_guillaume_a_la_fin_de_la_secheuse
    - automation.notifier_guillaume_a_la_fin_de_limpression
    - automation.notifier_guillaume_au_demarrage_de_ha
    - automation.notifier_guillaume_quand_le_chat_est_nourrit
    - automation.notifier_guillaume_si_basile_joue_avec_sa_lampe
    - automation.notifier_guillaume_si_louise_joue_avec_sa_lampe
    - automation.notifier_guillaume_si_on_sonne
    - automation.notifier_la_meteo_de_la_journee_a_guillaume_le_matin_jour_travaille
    - automation.notifier_lors_arrivee_philo
    - automation.notifier_philo_a_la_fin_de_la_secheuse
    - automation.notifier_philo_a_la_fin_de_limpression
    - automation.notifier_philo_si_basile_joue_avec_sa_lampe
    - automation.notifier_philo_si_louise_joue_avec_sa_lampe
    - automation.notifier_si_pawned
    - automation.philo_plus_a_la_maison
    - automation.philo_plus_a_la_maison_maj_parents
    - automation.philo_retour_a_la_maison
    - automation.philo_retour_a_la_maison_maj_parents
    - automation.vitesse_danimation_leds_salle_familiale
